apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orgchart
  name: orgchart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orgchart
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orgchart
    spec:
      containers:
      - image: jweissig/app:0.0.1
        imagePullPolicy: IfNotPresent
        name: app
