apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    avp.kubernetes.io/path: "mysecret/data/database/config"
    #avp.kubernetes.io/kv-version: "1"
type: Opaque
stringData:
  password: <password>
